name: Build Python Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Check-out repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'  # Specify the Python version
          architecture: 'x64'    # Optional, defaults to x64 if not specified
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          
      # Build Python script into a single executable or app folder (macOS)
      - name: Build Python executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: app
          enable-plugins: tk-inter

      # Upload built executable as an artifact
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/main.exe
          include-hidden-files: true
